---
title: "WOMEN IN MUSIC"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    #source_code: embed
    theme: journal

    css: style.css
    self_contained: false
---

<p style="border:3px; border-style:double; border-color:#ffffff; padding: 1em; font-family:Monaco; font-size:90%; text-align:center; font-weight:bold; color:#000000; background-color:#66ccff">
To what extent is the attitude towards gender representation in the music industry predicted by tone of the song and moderated by gender?
</p>

```{r setup, include = FALSE}
library(flexdashboard)
library(shiny)
library(jsonlite)
library(maptools)
library(ggplot2)
library(tidyr)
library(dplyr)
library(purrr)
library(leaflet)
library(plotly)
library(forcats)

wide <- read.csv("wide.csv")
long <- read.csv("long.csv")
averages <- read.csv("AveragePerQuestionPerSong.csv")
averages_both <- read.csv("AveragePerQuestionPerSongBoth.csv")

adding_attitude <- wide %>% 
  group_by(condition) %>%
  mutate(attitude=(Q1+Q2+Q3+Q4+Q5+Q6+Q7)/7)








```




Main Findings
======================================================




Column {.tabset data-width=175}
-----------------------------------------------------------------------

### Feminist

<iframe src="https://open.spotify.com/embed/playlist/7mWbXdE4Hky7MIt8BOjryX?utm_source=generator" width="100%" height="100%" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>

### Neutral

<iframe src="https://open.spotify.com/embed/playlist/2ttgDPSxCi9oPbOEQCrLvl?utm_source=generator" width="100%" height="100%" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>

Column {.tabset data-width=500}
-----------------------------------------------------------------------

### Q1

```{r}
averages %>%
  mutate(Song = fct_reorder(Song, desc(Order))) %>%
  ggplot(aes(x=Song, y=Q1, fill=Condition)) + geom_col(stat="identity", width=.4) + coord_flip() + ylim(0,6) + 
  labs(
    x = "",
    y = "Scale",
    title = "Explanation",
    subtitle = " (Q1) I enjoyed the lyrics of this excerpt") +
  scale_fill_manual(values=c("#ff6699", "#93C54B")) +
  theme_bw() +
  theme(
    text = element_text(family = "Palatino", size = 9)
  )
```

### Q2

```{r}
averages %>%
  mutate(Song = fct_reorder(Song, desc(Order))) %>%
  ggplot(aes(x=Song, y=Q2, fill=Condition)) + geom_col(stat="identity", width=.4) + coord_flip() + xlab("") + ylab("Scale") + theme_bw() + ylim(0,6) + ggtitle("I think these lyrics represented \n men and/or women fairly")

```

### Q3

```{r}
averages %>%
  mutate(Song = fct_reorder(Song, desc(Order))) %>%
  ggplot(aes(x=Song, y=Q3, fill=Condition)) + geom_col(stat="identity", width=.4) + coord_flip() + xlab("") + ylab("Scale") + theme_bw()  + ylim(0,6) + ggtitle("After listening to this excerpt, I feel positively \n about gender representation in music")
```

### Q4

```{r}
averages %>%
  mutate(Song = fct_reorder(Song, desc(Order))) %>%
  ggplot(aes(x=Song, y=Q4, fill=Condition)) + geom_col(stat="identity", width=.4) + coord_flip() + xlab("") + ylab("Scale") + theme_bw()  + ylim(0,6) + ggtitle("I feel represented in the lyrics I just heard")
```

### Q5

```{r}
averages %>%
  mutate(Song = fct_reorder(Song, desc(Order))) %>%
  ggplot(aes(x=Song, y=Q5, fill=Condition)) + geom_col(stat="identity", width=.4) + coord_flip() + xlab("") + ylab("Scale") + theme_bw()  + ylim(0,6) + ggtitle("These lyrics create a positive message")
```

### Q6

```{r}
averages %>%
  mutate(Song = fct_reorder(Song, desc(Order))) %>%
  ggplot(aes(x=Song, y=Q6, fill=Condition)) + geom_col(stat="identity", width=.4) + coord_flip() + xlab("") + ylab("Scale") + theme_bw()  + ylim(0,6) + ggtitle("These lyrics make me feel uncomfortable")
```

### Q7

```{r}
averages %>%
  mutate(Song = fct_reorder(Song, desc(Order))) %>%
  ggplot(aes(x=Song, y=Q7, fill=Condition)) + geom_col(stat="identity", width=.4) + coord_flip() + xlab("") + ylab("Scale") + theme_bw()  + ylim(0,6) + ggtitle("This excerpt had feminist connotations in its lyrics")
```


Column {data-width=350}
-----------------------------------------------------------------------

### Attitude difference

```{r}
ggplot(adding_attitude, aes(x = gender, y=attitude, fill = gender)) +
  geom_bar(position="dodge", stat="identity") + facet_grid(. ~ condition) +
  labs(
    x = "Gender",
    y = "Attitude",
    caption = "lol") +
  scale_fill_manual(values=c("#4BC5BA", "#7D4BC5")) +
  theme_bw() +
    theme(
    text = element_text(family = "Palatino", size = 10))
```

### Difference in gender representation in lyrics

```{r}
come <- averages_both %>%
  group_by(Gender) 

ggplot(come, aes(x = Song, y=Q4, fill = Gender)) +
  geom_bar(position="dodge", stat="identity") + facet_grid(Condition ~ .) +
  coord_flip() +
  labs(
    x = "",
    y = "Scale",
    caption = "lol") +
  scale_fill_manual(values=c("#4BC5BA", "#7D4BC5")) +
  theme_bw() +
    theme(
    text = element_text(family = "Palatino", size = 10))

```

Data
======================================================

Column
-----------------------------------------------------------------------

### Chart D

```{r }
```

Literature
======================================================

Column
-----------------------------------------------------------------------

### Chart D

```{r}

```

